import jsPDF from 'jspdf';
import 'jspdf-autotable';

const addBranding = (doc) => {
  doc.setFillColor(11, 15, 25); // brand-background
  doc.rect(0, 0, doc.internal.pageSize.width, 25, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text('AQUASHIELD AI', 14, 16);
  
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(10);
  doc.text('NATIONAL HEALTH INTELLIGENCE SYSTEM', doc.internal.pageSize.width - 14, 16, { align: 'right' });
};

const addFooter = (doc) => {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by AquaShield AI on ${new Date().toLocaleString()}`,
      14,
      doc.internal.pageSize.height - 10
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width - 14,
      doc.internal.pageSize.height - 10,
      { align: 'right' }
    );
  }
};

export const generateVillageReport = (village, reports, alerts) => {
  const doc = new jsPDF();
  addBranding(doc);
  
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.text(`Village Digital Twin Report: ${village.name}`, 14, 40);
  
  doc.setFontSize(12);
  doc.text(`District: ${village.district}, ${village.state}`, 14, 50);
  doc.text(`Population: ${village.population}`, 14, 58);
  doc.text(`Risk Score: ${village.riskScore?.toFixed(1)}%`, 14, 66);
  doc.text(`Water Quality: ${village.waterQualityStatus}`, 14, 74);
  doc.text(`Active Cases: ${village.activeCases}`, 14, 82);

  doc.setFontSize(14);
  doc.text('Recent Health Reports', 14, 100);
  
  const reportData = reports.slice(0, 10).map(r => [
    new Date(r.reportDate).toLocaleDateString(),
    r.symptoms,
    r.severity,
    r.status
  ]);
  
  doc.autoTable({
    startY: 105,
    head: [['Date', 'Symptoms', 'Severity', 'Status']],
    body: reportData,
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246] }
  });

  const finalY = doc.lastAutoTable.finalY || 105;
  
  doc.text('Active Alerts', 14, finalY + 15);
  const alertData = alerts.map(a => [
    new Date(a.createdAt).toLocaleDateString(),
    a.alertType,
    a.alertLevel,
    a.message
  ]);
  
  doc.autoTable({
    startY: finalY + 20,
    head: [['Date', 'Type', 'Level', 'Message']],
    body: alertData,
    theme: 'grid',
    headStyles: { fillColor: [239, 68, 68] }
  });

  addFooter(doc);
  doc.save(`Village_Report_${village.name.replace(/\s+/g, '_')}.pdf`);
};

export const generateAlertsReport = (alerts) => {
  const doc = new jsPDF();
  addBranding(doc);
  
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.text('National Alerts Overview Report', 14, 40);
  
  const alertData = alerts.map(a => [
    a.village?.name || 'Global',
    a.alertType,
    a.alertLevel,
    a.status,
    new Date(a.createdAt).toLocaleDateString()
  ]);
  
  doc.autoTable({
    startY: 50,
    head: [['Village', 'Type', 'Level', 'Status', 'Date']],
    body: alertData,
    theme: 'grid',
    headStyles: { fillColor: [245, 158, 11] }
  });

  addFooter(doc);
  doc.save(`Alert_Report_${new Date().getTime()}.pdf`);
};

export const generateHealthAssessment = (analytics) => {
  const doc = new jsPDF();
  addBranding(doc);
  
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.text('National Health Assessment', 14, 40);
  
  doc.setFontSize(12);
  doc.text(`Active Outbreaks: ${analytics.alertStats?.active || 0}`, 14, 55);
  doc.text(`Safe Water Sources: ${analytics.waterQuality?.safe || 0}`, 14, 65);
  doc.text(`Contaminated Sources: ${analytics.waterQuality?.unsafe || 0}`, 14, 75);

  doc.setFontSize(14);
  doc.text('District Risk Rankings', 14, 95);

  const districtData = (analytics.districtRanking || []).map(d => [
    d.district,
    d.activeCases,
    d.riskScore.toFixed(1) + '%'
  ]);

  doc.autoTable({
    startY: 100,
    head: [['District', 'Active Cases', 'Average Risk Score']],
    body: districtData,
    theme: 'grid',
    headStyles: { fillColor: [16, 185, 129] }
  });

  addFooter(doc);
  doc.save(`Health_Assessment_${new Date().getTime()}.pdf`);
};

export const generateRiskAnalysis = (villages) => {
  const doc = new jsPDF();
  addBranding(doc);
  
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.text('National Risk Analysis Matrix', 14, 40);
  
  doc.setFontSize(12);
  doc.text('High Risk Predictive Index:', 14, 55);

  const riskData = villages.map(v => [
    v.name,
    v.district,
    v.riskScore?.toFixed(1) + '%',
    v.waterQualityStatus,
    v.activeCases
  ]).sort((a, b) => parseFloat(b[2]) - parseFloat(a[2])); // sort by risk

  doc.autoTable({
    startY: 65,
    head: [['Village', 'District', 'Risk Score', 'Water Quality', 'Active Cases']],
    body: riskData,
    theme: 'grid',
    headStyles: { fillColor: [139, 92, 246] } // brand-accent/purple
  });

  addFooter(doc);
  doc.save(`Risk_Analysis_${new Date().getTime()}.pdf`);
};
